-- ============================================================
-- 租户表 DDL + 初始化数据
-- 数据库：example_db（PostgreSQL 16，docker-compose 中的 postgres 服务）
-- 账号：admin / password
--
-- 说明：
-- 1. Java 端 JPA 配置为 ddl-auto: validate，表必须先建好且结构匹配，应用才能启动。
-- 2. 列名为 snake_case，与实体 Tenant 的字段（驼峰）经 Hibernate 默认命名策略映射后一致。
-- 3. 执行方式（任选其一）：
--    docker exec -i postgres psql -U admin -d example_db < sql/tenant_init.sql
--    或 psql "postgresql://admin:password@localhost:5432/example_db" -f sql/tenant_init.sql
-- ============================================================

CREATE TABLE IF NOT EXISTS tenants (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            VARCHAR(255) NOT NULL UNIQUE,
    name                 VARCHAR(255) NOT NULL,
    collection_name      VARCHAR(255) NOT NULL,
    default_llm_provider VARCHAR(20)  DEFAULT 'deepseek',
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE  tenants                      IS '租户表：每个租户独立的知识库集合与默认模型';
COMMENT ON COLUMN tenants.tenant_id            IS '租户唯一标识（业务主键，检索隔离依据）';
COMMENT ON COLUMN tenants.name                 IS '租户名称';
COMMENT ON COLUMN tenants.collection_name      IS '该租户对应的向量/全文集合名';
COMMENT ON COLUMN tenants.default_llm_provider IS '默认大模型 provider：deepseek/qianwen/doubao';

-- ------------------------------------------------------------
-- 5 个租户初始化数据（幂等：按 tenant_id 冲突则更新）
-- ------------------------------------------------------------
INSERT INTO tenants (tenant_id, name, collection_name, default_llm_provider, created_at, updated_at) VALUES
    ('tenant_001', 'Acme SaaS',           'acme_kb',     'deepseek', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tenant_002', 'Globex E-commerce',   'globex_kb',   'qianwen',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tenant_003', 'Initech Fintech',     'initech_kb',  'doubao',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tenant_004', 'Umbrella Health',     'umbrella_kb', 'deepseek', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tenant_005', 'Stark Manufacturing', 'stark_kb',    'qianwen',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (tenant_id) DO UPDATE SET
    name                 = EXCLUDED.name,
    collection_name      = EXCLUDED.collection_name,
    default_llm_provider = EXCLUDED.default_llm_provider,
    updated_at           = CURRENT_TIMESTAMP;

-- 验证
-- SELECT id, tenant_id, name, collection_name, default_llm_provider FROM tenants ORDER BY id;
